require:
  - rubocop-rspec
  - rubocop-rails

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: ~
  DisplayCopNames: true
  Exclude:
    - bin/**/*
    - db/**/*
    - vendor/**/*
    - tmp/**/*

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Rails/UnknownEnv:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/RepeatedDescription:
  Enabled: false

RSpec/SharedExamples:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false

RSpec/MessageSpies:
  EnforcedStyle: receive

Capybara/FeatureMethods:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/CollectionMethods:
  Enabled: true

Style/SymbolArray:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

Style/EmptyMethod:
  EnforcedStyle: expanded
  SupportedStyles:
    - compact
    - expanded

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringMethods:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Enabled: false

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
  SupportedStyles:
    - with_first_parameter
    - with_fixed_indentation

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
  SupportedStylesAlignWith:
    - keyword
    - variable

RSpec/LetSetup:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/EmptyExampleGroup:
  Exclude:
    - "spec/api/**/*spec.rb"
    - "spec/support/shared_examples/api/*.rb"

RSpec/DescribeClass:
  Exclude:
    - "spec/lib/tasks/**/*spec.rb"

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"
