version: "3.4"

services:
  db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  app:
    image: ${IMAGE_NAME}
    environment:
      - DATABASE_URL=postgres://postgres:password@db
      - RAILS_ENV=test
      - RACK_ENV=test
      - DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL=true
    volumes:
      - ruby-bundle:/usr/local/bundle
      - .:/app

volumes:
  ruby-bundle:
  db-data: